### ISSUE TITLE
Extension crashing

### ISSUE THREAD

**Issue by werunom** [streetsidesoftware/vscode-spell-checker#375]
Of late, I have noticed the extension suddenly crashing. This was not a show-stopper as the extension started working after restarting the vscode.

Since this has happened few times (not too frequently though), I thought of reporting it here. Below is the log that was shown as soon as the extension crashed.

```
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x55b6424472b5  [/opt/visual-studio-code/code]
 2: 0x55b64244742a  [/opt/visual-studio-code/code]
 3: 0x55b63f0dc4f1  [/opt/visual-studio-code/code]
 4: 0x55b63f1896f2  [/opt/visual-studio-code/code]
 5: 0x55b63ed5b83a v8::internal::Factory::CopyWeakArrayListAndGrow(v8::internal::Handle<v8::internal::WeakArrayList>, int, v8::internal::PretenureFlag) [/opt/visual-studio-code/code]
 6: 0x55b63f1d1510  [/opt/visual-studio-code/code]
 7: 0x55b63f1d9297  [/opt/visual-studio-code/code]
 8: 0x55b63edbbe0c  [/opt/visual-studio-code/code]
 9: 0x55b63edc01dd  [/opt/visual-studio-code/code]
10: 0x55b63edc87e1  [/opt/visual-studio-code/code]
11: 0x55b63f34ad0e  [/opt/visual-studio-code/code]
[Info  - 8:37:56 PM] Connection to server got closed. Server will restart.
[Error - 8:37:56 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:17944)
	at Object.dispose (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:64145)
	at module.exports.t.LanguageClient.handleConnectionClosed (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:64320)
	at module.exports.t.LanguageClient.handleConnectionClosed (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:235344)
	at t (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:62521)
	at invoke (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:75332)
	at r.fire (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:76062)
	at K (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:10130)
	at invoke (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:75332)
	at r.fire (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:76062)
	at module.exports.t.IPCMessageReader.fireClose (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:78342)
	at ChildProcess.module.exports.t.IPCMessageReader.constructor.t.on (/home/varun/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.18/dist/extension.js:1:80323)
	at ChildProcess.emit (events.js:187:15)
	at maybeClose (internal/child_process.js:962:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by Jason3S** [comment]
Can you tell me about your environment?
Large files? Kind of files?

**Comment by werunom** [comment]
Excuse for not responding immediately. I usually work with `tex` and `txt` files. These files are on an average contain 10000 words. Sometimes, I also need to open multiple files of this size. (Mentioning this because I think cspell shows errors for all the open files). When the above crash happened, I was working with `tex` file of 13,000 words.

regarding environment, I work on `Manjaro KDE` and use the latest versions of vscode and cspell-extension.

Please do let me know what else I can provide or help. Thanks!

**Comment by Mingun** [comment]
I faced this problem too. Most likely it arises when the size of the checked files exceeds a certain limit because after restart expansion works without problems at the same file on which it crash.

**Comment by Jason3S** [comment]
@Mingun Do you know if it is the number of files or the size of a large file? I might need to change the way the extension deals with large files.

**Comment by Mingun** [comment]
I think, that is accumulated size of checked files. So, I have several big opened files after VS Code opened.  I edit one of them, all right. Then I edit another, and another and after some point extension crashed. If I restart VS Code, then at the same file, on which extension crashed it continue work normally. If I repeat actions, described above, extension can crash on another file.

**Comment by damianoazzolini** [comment]
Same issue for me. I use vscode in WSL for windows 10. My file is a .tex file with 1960 lines. Here the trace:
```
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x98edf0 node::Abort() [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 2: 0x98fe56 node::OnFatalError(char const*, char const*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 3: 0xb1552e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 4: 0xb158a9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 5: 0xf20105  [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 6: 0xefe9c5 v8::internal::Factory::CopyWeakArrayListAndGrow(v8::internal::Handle<v8::internal::WeakArrayList>, int, v8::internal::PretenureFlag) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 7: 0x10470ea v8::internal::WeakArrayList::EnsureSpace(v8::internal::Isolate*, v8::internal::Handle<v8::internal::WeakArrayList>, int, v8::internal::PretenureFlag) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 8: 0x10473ab v8::internal::PrototypeUsers::Add(v8::internal::Isolate*, v8::internal::Handle<v8::internal::WeakArrayList>, v8::internal::Handle<v8::internal::Map>, int*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
 9: 0x10a4184 v8::internal::JSObject::LazyRegisterPrototypeUser(v8::internal::Handle<v8::internal::Map>, v8::internal::Isolate*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
10: 0x10c0084 v8::internal::Map::GetOrCreatePrototypeChainValidityCell(v8::internal::Handle<v8::internal::Map>, v8::internal::Isolate*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
11: 0xfa024c v8::internal::LoadHandler::LoadFromPrototype(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Smi>, v8::internal::MaybeObjectHandle, v8::internal::MaybeObjectHandle) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
12: 0xfa9200 v8::internal::LoadIC::ComputeHandler(v8::internal::LookupIterator*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
13: 0xfb0aa1 v8::internal::LoadIC::UpdateCaches(v8::internal::LookupIterator*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
14: 0xfb11dc v8::internal::LoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
15: 0xfb5a39 v8::internal::Runtime_LoadIC_Miss(int, unsigned long*, v8::internal::Isolate*) [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
16: 0x1a93942  [/home/damiano/.vscode-server/bin/78a4c91400152c0f27ba4d363eb56d2835f9903a/node]
```
After that it prints a connection error:
```
[Info  - 10:45:57] Connection to server got closed. Server will restart.
[Error - 10:45:57] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:73987)
	at Object.dispose (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:57265)
	at R.handleConnectionClosed (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:57439)
	at R.handleConnectionClosed (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:243044)
	at t (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:55590)
	at invoke (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:81136)
	at r.fire (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:81866)
	at V (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:65896)
	at invoke (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:81136)
	at r.fire (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:81866)
	at t.IPCMessageReader.fireClose (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:86322)
	at ChildProcess.<anonymous> (/home/damiano/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.8.0/dist/extension.js:1:88303)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by Jason3S** [comment]
@damianoazzolini Do you have a sample file I can try? 1960 lines should not be a problem.

**Comment by damianoazzolini** [comment]
@Jason3S sorry for the delay. Unfortunately, i cannot share with you the file. However, the issue rarely happens. Most of the time the extension works well. Another issue i've noticed is that the extension silently seems to stop working. That is, at certain point of the text, if i write a word which is not correct, it does not get marked.

**Comment by Jason3S** [comment]
Closing as stale.
