### ISSUE TITLE
Expansion crashes when starting up

### ISSUE THREAD

**Issue by bheemann** [streetsidesoftware/vscode-spell-checker#388]
Installed version [1.7.18] and it crashes when starting up:

`Error: Cannot find module 'c:\Users\benja\.vscode\extensions\streetsidesoftware.code-spell-checker-1.7.18\server\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
[Error - 10:44:36] Connection to server got closed. Server will not be restarted.`

Visual Studio Code Version:
![verVSCode](https://user-images.githubusercontent.com/24730923/66698460-96e51080-ecde-11e9-8dfc-67cea59d918d.PNG)

reinstallation and restarting vs code didn't help.

any ideas?

**Comment by Jason3S** [comment]
Sometimes VS Code doesn't correctly install it.

1. Uninstall the extension.
1. Quit VS Code.
1. Delete any directories like: `c:\Users\benja\.vscode\extensions\streetsidesoftware.code-spell-checker-*`
1. Start VS Code and re-install the spell checker.

**Comment by pgrm** [comment]
@Jason3S 

I have a similar issue, for me the extension is broken on VSCode when using WSL: Ubuntu. I have the version 1.7.20. The error

```
Error: Cannot find module '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

but, when I check `ls /home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js` I can see that the file exists. I've tried re-installing it, I've tried deleting the local files, like you mentioned, but none of that worked. Any other ideas?

**Comment by Jason3S** [comment]
@pgrm you have to delete that directory and re-install. For some reason it did not download correctly.

**Comment by pgrm** [comment]
@Jason3S I did that - and I couldn't find any other directories - `find . -name "streetsidesoftware.code-spell-checker-*"` didn't return anything else except for a folder in `.directory_history`

This is the full stack trace after it got re-installed, after I removed every trace of it

```
fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Object.realpathSync (fs.js:1470:7)
    at toRealPath (internal/modules/cjs/loader.js:268:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:349:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:27)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
}
[Info  - 9:30:54 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 9:30:54 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 9:30:55 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 9:30:56 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/home/my_user/.vscode-server/extensions/streetsidesoftware.code-spell-checker-1.7.20/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 9:30:56 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by Jason3S** [comment]
That is super frustrating.

**Comment by Jason3S** [comment]
This seems to be a VS Code Server issue.
I have never tried it. I'll take a look.

**Comment by Jason3S** [comment]
@pgrm,
I published a new version now supports [Visual Studio Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview).

I'm going to close this issue, since it wasn't related to Remote Development, but to the extension not fully installing.
