### ISSUE TITLE
Error message about server on startup - died.

### ISSUE THREAD

**Issue by liubomirwm** [streetsidesoftware/vscode-spell-checker#467]
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module 'crypto-random-string'
Require stack:
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/unique-string/index.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/configstore/index.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/Settings/index.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/index.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/validator.js
- /home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/unique-string/index.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/unique-string/index.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/configstore/index.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/Settings/index.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/node_modules/cspell-lib/dist/index.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/validator.js',
    '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js'
  ]
}
[Info  - 19:59:46] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 19:59:46] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 19:59:46] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Info  - 19:59:46] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:720
    throw err;
    ^

Error: Cannot find module '/home/lyubomir/.vscode/extensions/streetsidesoftware.code-spell-checker-1.8.0/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.Module.runMain (internal/modules/cjs/loader.js:944:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[Error - 19:59:46] Connection to server got closed. Server will not be restarted.

**Comment by Jason3S** [comment]
Please see #388 
Would you let me know if that works for you?
