### ISSUE TITLE
plugin missing stringify?

### ISSUE THREAD

**Issue by isaiahfrantz** [streetsidesoftware/vscode-spell-checker#572]
I assume that this dependancy should be shipped with the spell-checker plugin but Im not seeing anybody complaining about it anywhere so any help would be appreciated.

I do run vscode-insiders so maybe thats it?
Anyway, a few days ago I started getting language server crashes at code startup:
```
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module './lib/stringify'
Require stack:
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/braces/index.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/micromatch/index.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/cspell-glob/lib/GlobMatcher.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/cspell-glob/lib/index.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/documentSettings.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/codeActions.js
- /home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:899:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/braces/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1014:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
    at Module.load (internal/modules/cjs/loader.js:862:32)
    at Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/braces/index.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/micromatch/index.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/cspell-glob/lib/GlobMatcher.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/node_modules/cspell-glob/lib/index.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/documentSettings.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/codeActions.js',
    '/home/user/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.2/server/server.js'
  ]
}
[Error - 8:14:38 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by Jason3S** [comment]
Thank you. I'll try it with Insiders.

**Comment by Jason3S** [comment]
Something to try:
1. Uninstall the extension
1. Remove it from the VS code cache: `~/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-*`
1. Reinstall the extension

**Comment by isaiahfrantz** [comment]
That worked
Thanks!
