### ISSUE TITLE
Server problem with version 1.9.3 

### ISSUE THREAD

**Issue by inwardmovement** [streetsidesoftware/vscode-spell-checker#577]
There is a server problem with version `1.9.3`. It's ok when I load `1.9.2`.

![image](https://user-images.githubusercontent.com/9438102/98665980-ace35b80-234c-11eb-9dac-28d6209c104a.png)
```

Version: 1.51.0 (user setup)
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:18:23.642Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by Jason3S** [comment]
This can happen when it doesn't properly install.
Try uninstalling it. You might need to delete it from the VS Code cache.

Any errors that show up in the extension host would be useful:
![image](https://user-images.githubusercontent.com/3740137/98708717-c5ba3400-2381-11eb-92d6-32ff3365ebce.png)

**Comment by inwardmovement** [comment]
I tried reinstalling but the problem is still here with last version.
Here is the output:

```
[2020-11-10 19:08:39.602] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:08:39.602] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3/dist/extension.js
[2020-11-10 19:08:40.487] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker-french-reforme {"startup":false,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:08:40.488] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-french-reforme-0.1.6/out/src/extension
[2020-11-10 19:13:01.124] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:13:01.124] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3/dist/extension.js
[2020-11-10 19:13:01.570] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker-french-reforme {"startup":false,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:13:01.570] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-french-reforme-0.1.6/out/src/extension
[2020-11-10 19:13:43.741] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2020-11-10 19:13:43.741] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3/dist/extension.js
[2020-11-10 19:14:28.599] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":false,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2020-11-10 19:14:28.599] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3/dist/extension.js
[2020-11-10 19:14:40.989] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker-french-reforme {"startup":false,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:14:40.989] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-french-reforme-0.1.6/out/src/extension
[2020-11-10 19:15:00.574] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:15:00.574] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3/dist/extension.js
[2020-11-10 19:15:01.408] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker-french-reforme {"startup":false,"extensionId":{"value":"streetsidesoftware.code-spell-checker-french-reforme","_lower":"streetsidesoftware.code-spell-checker-french-reforme"},"activationEvent":"*"}
[2020-11-10 19:15:01.408] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/arkay/.vscode/extensions/streetsidesoftware.code-spell-checker-french-reforme-0.1.6/out/src/extension
```

**Comment by inwardmovement** [comment]
In the output of Code Spell Checker I have this:

```
internal/modules/cjs/loader.js:847
    throw err;
    ^

Error: Cannot find module './c:/Users/arkay/Documents/cspell-dicts/packages/fr_FR_90/cspell-ext.json'
Require stack:
- c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\cspell-lib\dist\Settings\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at resolveFileName (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\resolve-from\index.js:43:9)
    at Object.module.exports [as default] (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\resolve-from\index.js:46:47)
    at resolveFilename (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:253:38)
    at c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:68:22
    at Array.map (<anonymous>)
    at normalizeSettings (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:68:10)
    at Object.getGlobalSettings (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:268:16)
    at Object.<anonymous> (c:\Users\arkay\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.3\server\server.js:32:71) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'c:\\Users\\arkay\\.vscode\\extensions\\streetsidesoftware.code-spell-checker-1.9.3\\server\\node_modules\\cspell-lib\\dist\\Settings\\noop.js'
  ]
}
[Error - 08:27:47] Connection to server got closed. Server will not be restarted.
```

**Comment by liby** [comment]
The problem I encountered is the same as described by @inwardmovement, including log output.

Uninstalling this extension and removing the `$HOME/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3` folder and reinstalling seems to solve this problem.

**Comment by inwardmovement** [comment]
> Uninstalling this extension and removing the `$HOME/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.3` folder and reinstalling seems to solve this problem.

Unfortunately not for me

**Comment by Jason3S** [comment]
@inwardmovement In your case, it is not able to find the French dictionary:
`c:/Users/arkay/Documents/cspell-dicts/packages/fr_FR_90/cspell-ext.json`

Still, the server should NOT crash if the dictionary cannot be found.

**Comment by inwardmovement** [comment]
Thanks for the fix.

I do not have the notification about not finding module `.../cspell-dicts/packages/fr_FR_90/cspell-ext.json` any more, does it mean it is now able to find the dictionary?
