### ISSUE TITLE
The Code Spell Checker server crashed 5 times in the last 3 minutes error

### ISSUE THREAD

**Issue by vccolombo** [streetsidesoftware/vscode-spell-checker#591]
Hello!

I'm receiving a "The Code Spell Checker server crashed 5 times in the last 3 minutes. The server will not be restarted" error when I open vscode. 

Here is the error log:

```terminal
Error: Cannot find module '/home/vccolombo/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.4/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

The folder `/home/vccolombo/.vscode/extensions/streetsidesoftware.code-spell-checker-1.9.4/server/` exists, but there is no server.js inside.

It was working a few days ago, but now it stopped. I already tried removing and reinstalling the extension.

My vscode info:

```
Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.3.18-lp152.50-default
```

My OS is a Linux openSUSE Leap 15.2 x64

**Comment by vccolombo** [comment]
Apparently a duplicate of #577 and https://github.com/streetsidesoftware/vscode-spell-checker/issues/577#issuecomment-726480179 solved the issue for me. Thanks for your time
