### ISSUE TITLE
Language server chrash

### ISSUE THREAD

**Issue by slrtbtfs** [streetsidesoftware/vscode-spell-checker#654]
See stack trace.

Unfortunately I haven't figured out a way to reproduce this crash, yet.

```
Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Error - 4:39:42 PM] Connection to server got closed. Server will not be restarted.

**Comment by Jason3S** [comment]
That can happen if it isn't fully installed.

The problem is that VS Code keep a cached copy around, so uninstalling / reinstalling doesn't work.

Steps from #388 

1. Uninstall the extension.
1. Quit VS Code.
1. Delete any directories like: `/home/slrtbtfs/.vscode/extensions/streetsidesoftware.code-spell-checker-*`
1. Start VS Code and re-install the spell checker.

**Comment by slrtbtfs** [comment]
Thanks!
