### ISSUE TITLE
 recently plugin fails to start with "no such file or directory, uv_cwd" error

### ISSUE THREAD

**Issue by maxandersen** [streetsidesoftware/vscode-spell-checker#684]
not sure what changed but I had to disable this plugin as it keeps erroring at startup. 
Here are the logs when I do: `code .`

```
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Info  - 10:08:14 AM] Connection to server got closed. Server will restart.
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Info  - 10:08:14 AM] Connection to server got closed. Server will restart.
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Info  - 10:08:14 AM] Connection to server got closed. Server will restart.
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Info  - 10:08:15 AM] Connection to server got closed. Server will restart.
internal/process/main_thread_only.js:42
    cachedCwd = binding.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.cwd (internal/process/main_thread_only.js:42:25)
    at process.cwd (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/graceful-fs/polyfills.js:10:19)
    at Object.resolve (path.js:978:47)
    at Object.resolveFile (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/util/resolveFile.js:42:26)
    at resolveFilename (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:258:29)
    at /Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:24
    at CommentArray.map (<anonymous>)
    at normalizeSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:71:10)
    at importSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:106:37)
    at Object.readSettings (/Users/max/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-lib/dist/Settings/CSpellSettingsServer.js:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
[Error - 10:08:15 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by maxandersen** [comment]
oh and if I don't disable it vscode does not actually open the folder/file passed into - hence why I need to disable it.

**Comment by Jason3S** [comment]
It is an issue with VS Code. It doesn't properly install the extension.

See https://github.com/streetsidesoftware/vscode-spell-checker/issues/654#issuecomment-755454263 on how to fix it.
